version: '3.8'

services:
  app:
    container_name: lojacorr_app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - "8002:8000"
    networks:
      - laravel-net
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: lojacorr_db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel-net

volumes:
  db_data:

networks:
  laravel-net:
    driver: bridge
